### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by billi95** [austinwebber/W101-PD-Script#3]
I have to say that I can't get it to run no matter what I do.
1. Download the zip "W101-PD-Script-1.4.zip"
2. extract folder "W101-PD-Script-1.4"
3. Start "PetDanceScript.exe"
4. Select any World, Any Snack and put in game amount
5. Press start
and then nothing happens. Doesn't press X to start the game selection, does't move the mouse to select a world and start, doesn't press the buttons.

**Comment by austinwebber** [comment]
Before it completes any of the actions, it activates the W101 game window and does a color detection on the screen to determine if you are at the pet dance game. Therefore, I suspect there is something wrong with the settings you've set and which version of the game you are using. If it isn't selecting the window, that may be why no further actions are occurring.

**Comment by 1aghunter** [comment]
I think that some people can only use 800x600 res rather than 800x400. with the slightly higher res the cursor misses the game start button and it messes the script up. Not 100% sure tho
